# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project dependency file
COPY pyproject.toml ./
COPY uv.lock ./

# Install pip and build dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir hatchling

# Copy entire project
COPY . .

# Install project in editable mode
RUN pip install --no-cache-dir .

# Expose any required ports if needed (if the server listens on a specific port)
EXPOSE 8000

# Default command to launch the MCP server
CMD ["mcp-server-appwrite"]
